// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net-x-msg-im-hlr-group.proto

#ifndef PROTOBUF_net_2dx_2dmsg_2dim_2dhlr_2dgroup_2eproto__INCLUDED
#define PROTOBUF_net_2dx_2dmsg_2dim_2dhlr_2dgroup_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_net_2dx_2dmsg_2dim_2dhlr_2dgroup_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsXmsgImHlrGroupMsgReqImpl();
void InitDefaultsXmsgImHlrGroupMsgReq();
void InitDefaultsXmsgImHlrGroupMsgRsp_ExtEntry_DoNotUseImpl();
void InitDefaultsXmsgImHlrGroupMsgRsp_ExtEntry_DoNotUse();
void InitDefaultsXmsgImHlrGroupMsgRspImpl();
void InitDefaultsXmsgImHlrGroupMsgRsp();
inline void InitDefaults() {
  InitDefaultsXmsgImHlrGroupMsgReq();
  InitDefaultsXmsgImHlrGroupMsgRsp_ExtEntry_DoNotUse();
  InitDefaultsXmsgImHlrGroupMsgRsp();
}
}  // namespace protobuf_net_2dx_2dmsg_2dim_2dhlr_2dgroup_2eproto
class XmsgImHlrGroupMsgReq;
class XmsgImHlrGroupMsgReqDefaultTypeInternal;
extern XmsgImHlrGroupMsgReqDefaultTypeInternal _XmsgImHlrGroupMsgReq_default_instance_;
class XmsgImHlrGroupMsgRsp;
class XmsgImHlrGroupMsgRspDefaultTypeInternal;
extern XmsgImHlrGroupMsgRspDefaultTypeInternal _XmsgImHlrGroupMsgRsp_default_instance_;
class XmsgImHlrGroupMsgRsp_ExtEntry_DoNotUse;
class XmsgImHlrGroupMsgRsp_ExtEntry_DoNotUseDefaultTypeInternal;
extern XmsgImHlrGroupMsgRsp_ExtEntry_DoNotUseDefaultTypeInternal _XmsgImHlrGroupMsgRsp_ExtEntry_DoNotUse_default_instance_;

// ===================================================================

class XmsgImHlrGroupMsgReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:XmsgImHlrGroupMsgReq) */ {
 public:
  XmsgImHlrGroupMsgReq();
  virtual ~XmsgImHlrGroupMsgReq();

  XmsgImHlrGroupMsgReq(const XmsgImHlrGroupMsgReq& from);

  inline XmsgImHlrGroupMsgReq& operator=(const XmsgImHlrGroupMsgReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  XmsgImHlrGroupMsgReq(XmsgImHlrGroupMsgReq&& from) noexcept
    : XmsgImHlrGroupMsgReq() {
    *this = ::std::move(from);
  }

  inline XmsgImHlrGroupMsgReq& operator=(XmsgImHlrGroupMsgReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const XmsgImHlrGroupMsgReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const XmsgImHlrGroupMsgReq* internal_default_instance() {
    return reinterpret_cast<const XmsgImHlrGroupMsgReq*>(
               &_XmsgImHlrGroupMsgReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(XmsgImHlrGroupMsgReq* other);
  friend void swap(XmsgImHlrGroupMsgReq& a, XmsgImHlrGroupMsgReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline XmsgImHlrGroupMsgReq* New() const PROTOBUF_FINAL { return New(NULL); }

  XmsgImHlrGroupMsgReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const XmsgImHlrGroupMsgReq& from);
  void MergeFrom(const XmsgImHlrGroupMsgReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(XmsgImHlrGroupMsgReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string cgt = 1;
  void clear_cgt();
  static const int kCgtFieldNumber = 1;
  const ::std::string& cgt() const;
  void set_cgt(const ::std::string& value);
  #if LANG_CXX11
  void set_cgt(::std::string&& value);
  #endif
  void set_cgt(const char* value);
  void set_cgt(const char* value, size_t size);
  ::std::string* mutable_cgt();
  ::std::string* release_cgt();
  void set_allocated_cgt(::std::string* cgt);

  // string type = 2;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  #if LANG_CXX11
  void set_type(::std::string&& value);
  #endif
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // string msg = 3;
  void clear_msg();
  static const int kMsgFieldNumber = 3;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_msg(::std::string&& value);
  #endif
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // bytes dat = 4;
  void clear_dat();
  static const int kDatFieldNumber = 4;
  const ::std::string& dat() const;
  void set_dat(const ::std::string& value);
  #if LANG_CXX11
  void set_dat(::std::string&& value);
  #endif
  void set_dat(const char* value);
  void set_dat(const void* value, size_t size);
  ::std::string* mutable_dat();
  ::std::string* release_dat();
  void set_allocated_dat(::std::string* dat);

  // @@protoc_insertion_point(class_scope:XmsgImHlrGroupMsgReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr cgt_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::internal::ArenaStringPtr dat_;
  mutable int _cached_size_;
  friend struct ::protobuf_net_2dx_2dmsg_2dim_2dhlr_2dgroup_2eproto::TableStruct;
  friend void ::protobuf_net_2dx_2dmsg_2dim_2dhlr_2dgroup_2eproto::InitDefaultsXmsgImHlrGroupMsgReqImpl();
};
// -------------------------------------------------------------------

class XmsgImHlrGroupMsgRsp_ExtEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<XmsgImHlrGroupMsgRsp_ExtEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<XmsgImHlrGroupMsgRsp_ExtEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  XmsgImHlrGroupMsgRsp_ExtEntry_DoNotUse();
  XmsgImHlrGroupMsgRsp_ExtEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const XmsgImHlrGroupMsgRsp_ExtEntry_DoNotUse& other);
  static const XmsgImHlrGroupMsgRsp_ExtEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const XmsgImHlrGroupMsgRsp_ExtEntry_DoNotUse*>(&_XmsgImHlrGroupMsgRsp_ExtEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class XmsgImHlrGroupMsgRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:XmsgImHlrGroupMsgRsp) */ {
 public:
  XmsgImHlrGroupMsgRsp();
  virtual ~XmsgImHlrGroupMsgRsp();

  XmsgImHlrGroupMsgRsp(const XmsgImHlrGroupMsgRsp& from);

  inline XmsgImHlrGroupMsgRsp& operator=(const XmsgImHlrGroupMsgRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  XmsgImHlrGroupMsgRsp(XmsgImHlrGroupMsgRsp&& from) noexcept
    : XmsgImHlrGroupMsgRsp() {
    *this = ::std::move(from);
  }

  inline XmsgImHlrGroupMsgRsp& operator=(XmsgImHlrGroupMsgRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const XmsgImHlrGroupMsgRsp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const XmsgImHlrGroupMsgRsp* internal_default_instance() {
    return reinterpret_cast<const XmsgImHlrGroupMsgRsp*>(
               &_XmsgImHlrGroupMsgRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(XmsgImHlrGroupMsgRsp* other);
  friend void swap(XmsgImHlrGroupMsgRsp& a, XmsgImHlrGroupMsgRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline XmsgImHlrGroupMsgRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  XmsgImHlrGroupMsgRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const XmsgImHlrGroupMsgRsp& from);
  void MergeFrom(const XmsgImHlrGroupMsgRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(XmsgImHlrGroupMsgRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, string> ext = 1;
  int ext_size() const;
  void clear_ext();
  static const int kExtFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      ext() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_ext();

  // @@protoc_insertion_point(class_scope:XmsgImHlrGroupMsgRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      XmsgImHlrGroupMsgRsp_ExtEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > ext_;
  mutable int _cached_size_;
  friend struct ::protobuf_net_2dx_2dmsg_2dim_2dhlr_2dgroup_2eproto::TableStruct;
  friend void ::protobuf_net_2dx_2dmsg_2dim_2dhlr_2dgroup_2eproto::InitDefaultsXmsgImHlrGroupMsgRspImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// XmsgImHlrGroupMsgReq

// string cgt = 1;
inline void XmsgImHlrGroupMsgReq::clear_cgt() {
  cgt_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XmsgImHlrGroupMsgReq::cgt() const {
  // @@protoc_insertion_point(field_get:XmsgImHlrGroupMsgReq.cgt)
  return cgt_.GetNoArena();
}
inline void XmsgImHlrGroupMsgReq::set_cgt(const ::std::string& value) {
  
  cgt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:XmsgImHlrGroupMsgReq.cgt)
}
#if LANG_CXX11
inline void XmsgImHlrGroupMsgReq::set_cgt(::std::string&& value) {
  
  cgt_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:XmsgImHlrGroupMsgReq.cgt)
}
#endif
inline void XmsgImHlrGroupMsgReq::set_cgt(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  cgt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:XmsgImHlrGroupMsgReq.cgt)
}
inline void XmsgImHlrGroupMsgReq::set_cgt(const char* value, size_t size) {
  
  cgt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:XmsgImHlrGroupMsgReq.cgt)
}
inline ::std::string* XmsgImHlrGroupMsgReq::mutable_cgt() {
  
  // @@protoc_insertion_point(field_mutable:XmsgImHlrGroupMsgReq.cgt)
  return cgt_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XmsgImHlrGroupMsgReq::release_cgt() {
  // @@protoc_insertion_point(field_release:XmsgImHlrGroupMsgReq.cgt)
  
  return cgt_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XmsgImHlrGroupMsgReq::set_allocated_cgt(::std::string* cgt) {
  if (cgt != NULL) {
    
  } else {
    
  }
  cgt_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cgt);
  // @@protoc_insertion_point(field_set_allocated:XmsgImHlrGroupMsgReq.cgt)
}

// string type = 2;
inline void XmsgImHlrGroupMsgReq::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XmsgImHlrGroupMsgReq::type() const {
  // @@protoc_insertion_point(field_get:XmsgImHlrGroupMsgReq.type)
  return type_.GetNoArena();
}
inline void XmsgImHlrGroupMsgReq::set_type(const ::std::string& value) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:XmsgImHlrGroupMsgReq.type)
}
#if LANG_CXX11
inline void XmsgImHlrGroupMsgReq::set_type(::std::string&& value) {
  
  type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:XmsgImHlrGroupMsgReq.type)
}
#endif
inline void XmsgImHlrGroupMsgReq::set_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:XmsgImHlrGroupMsgReq.type)
}
inline void XmsgImHlrGroupMsgReq::set_type(const char* value, size_t size) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:XmsgImHlrGroupMsgReq.type)
}
inline ::std::string* XmsgImHlrGroupMsgReq::mutable_type() {
  
  // @@protoc_insertion_point(field_mutable:XmsgImHlrGroupMsgReq.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XmsgImHlrGroupMsgReq::release_type() {
  // @@protoc_insertion_point(field_release:XmsgImHlrGroupMsgReq.type)
  
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XmsgImHlrGroupMsgReq::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    
  } else {
    
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:XmsgImHlrGroupMsgReq.type)
}

// string msg = 3;
inline void XmsgImHlrGroupMsgReq::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XmsgImHlrGroupMsgReq::msg() const {
  // @@protoc_insertion_point(field_get:XmsgImHlrGroupMsgReq.msg)
  return msg_.GetNoArena();
}
inline void XmsgImHlrGroupMsgReq::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:XmsgImHlrGroupMsgReq.msg)
}
#if LANG_CXX11
inline void XmsgImHlrGroupMsgReq::set_msg(::std::string&& value) {
  
  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:XmsgImHlrGroupMsgReq.msg)
}
#endif
inline void XmsgImHlrGroupMsgReq::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:XmsgImHlrGroupMsgReq.msg)
}
inline void XmsgImHlrGroupMsgReq::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:XmsgImHlrGroupMsgReq.msg)
}
inline ::std::string* XmsgImHlrGroupMsgReq::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:XmsgImHlrGroupMsgReq.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XmsgImHlrGroupMsgReq::release_msg() {
  // @@protoc_insertion_point(field_release:XmsgImHlrGroupMsgReq.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XmsgImHlrGroupMsgReq::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:XmsgImHlrGroupMsgReq.msg)
}

// bytes dat = 4;
inline void XmsgImHlrGroupMsgReq::clear_dat() {
  dat_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XmsgImHlrGroupMsgReq::dat() const {
  // @@protoc_insertion_point(field_get:XmsgImHlrGroupMsgReq.dat)
  return dat_.GetNoArena();
}
inline void XmsgImHlrGroupMsgReq::set_dat(const ::std::string& value) {
  
  dat_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:XmsgImHlrGroupMsgReq.dat)
}
#if LANG_CXX11
inline void XmsgImHlrGroupMsgReq::set_dat(::std::string&& value) {
  
  dat_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:XmsgImHlrGroupMsgReq.dat)
}
#endif
inline void XmsgImHlrGroupMsgReq::set_dat(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  dat_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:XmsgImHlrGroupMsgReq.dat)
}
inline void XmsgImHlrGroupMsgReq::set_dat(const void* value, size_t size) {
  
  dat_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:XmsgImHlrGroupMsgReq.dat)
}
inline ::std::string* XmsgImHlrGroupMsgReq::mutable_dat() {
  
  // @@protoc_insertion_point(field_mutable:XmsgImHlrGroupMsgReq.dat)
  return dat_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XmsgImHlrGroupMsgReq::release_dat() {
  // @@protoc_insertion_point(field_release:XmsgImHlrGroupMsgReq.dat)
  
  return dat_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XmsgImHlrGroupMsgReq::set_allocated_dat(::std::string* dat) {
  if (dat != NULL) {
    
  } else {
    
  }
  dat_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), dat);
  // @@protoc_insertion_point(field_set_allocated:XmsgImHlrGroupMsgReq.dat)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// XmsgImHlrGroupMsgRsp

// map<string, string> ext = 1;
inline int XmsgImHlrGroupMsgRsp::ext_size() const {
  return ext_.size();
}
inline void XmsgImHlrGroupMsgRsp::clear_ext() {
  ext_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
XmsgImHlrGroupMsgRsp::ext() const {
  // @@protoc_insertion_point(field_map:XmsgImHlrGroupMsgRsp.ext)
  return ext_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
XmsgImHlrGroupMsgRsp::mutable_ext() {
  // @@protoc_insertion_point(field_mutable_map:XmsgImHlrGroupMsgRsp.ext)
  return ext_.MutableMap();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_net_2dx_2dmsg_2dim_2dhlr_2dgroup_2eproto__INCLUDED
