// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net-x-msg-im-group-member.proto

#ifndef PROTOBUF_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto__INCLUDED
#define PROTOBUF_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "net-x-msg-im-group-usr.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[12];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsXmsgImGroupMemberAddReqImpl();
void InitDefaultsXmsgImGroupMemberAddReq();
void InitDefaultsXmsgImGroupMemberAddRsp_ExtEntry_DoNotUseImpl();
void InitDefaultsXmsgImGroupMemberAddRsp_ExtEntry_DoNotUse();
void InitDefaultsXmsgImGroupMemberAddRspImpl();
void InitDefaultsXmsgImGroupMemberAddRsp();
void InitDefaultsXmsgImGroupMemberQueryReqImpl();
void InitDefaultsXmsgImGroupMemberQueryReq();
void InitDefaultsXmsgImGroupMemberQueryRspImpl();
void InitDefaultsXmsgImGroupMemberQueryRsp();
void InitDefaultsXmsgImGroupMemberUpdateReq_UpsertEntry_DoNotUseImpl();
void InitDefaultsXmsgImGroupMemberUpdateReq_UpsertEntry_DoNotUse();
void InitDefaultsXmsgImGroupMemberUpdateReqImpl();
void InitDefaultsXmsgImGroupMemberUpdateReq();
void InitDefaultsXmsgImGroupMemberUpdateRsp_ExtEntry_DoNotUseImpl();
void InitDefaultsXmsgImGroupMemberUpdateRsp_ExtEntry_DoNotUse();
void InitDefaultsXmsgImGroupMemberUpdateRspImpl();
void InitDefaultsXmsgImGroupMemberUpdateRsp();
void InitDefaultsXmsgImGroupMemberDeleteReqImpl();
void InitDefaultsXmsgImGroupMemberDeleteReq();
void InitDefaultsXmsgImGroupMemberDeleteRsp_ExtEntry_DoNotUseImpl();
void InitDefaultsXmsgImGroupMemberDeleteRsp_ExtEntry_DoNotUse();
void InitDefaultsXmsgImGroupMemberDeleteRspImpl();
void InitDefaultsXmsgImGroupMemberDeleteRsp();
inline void InitDefaults() {
  InitDefaultsXmsgImGroupMemberAddReq();
  InitDefaultsXmsgImGroupMemberAddRsp_ExtEntry_DoNotUse();
  InitDefaultsXmsgImGroupMemberAddRsp();
  InitDefaultsXmsgImGroupMemberQueryReq();
  InitDefaultsXmsgImGroupMemberQueryRsp();
  InitDefaultsXmsgImGroupMemberUpdateReq_UpsertEntry_DoNotUse();
  InitDefaultsXmsgImGroupMemberUpdateReq();
  InitDefaultsXmsgImGroupMemberUpdateRsp_ExtEntry_DoNotUse();
  InitDefaultsXmsgImGroupMemberUpdateRsp();
  InitDefaultsXmsgImGroupMemberDeleteReq();
  InitDefaultsXmsgImGroupMemberDeleteRsp_ExtEntry_DoNotUse();
  InitDefaultsXmsgImGroupMemberDeleteRsp();
}
}  // namespace protobuf_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto
class XmsgImGroupMemberAddReq;
class XmsgImGroupMemberAddReqDefaultTypeInternal;
extern XmsgImGroupMemberAddReqDefaultTypeInternal _XmsgImGroupMemberAddReq_default_instance_;
class XmsgImGroupMemberAddRsp;
class XmsgImGroupMemberAddRspDefaultTypeInternal;
extern XmsgImGroupMemberAddRspDefaultTypeInternal _XmsgImGroupMemberAddRsp_default_instance_;
class XmsgImGroupMemberAddRsp_ExtEntry_DoNotUse;
class XmsgImGroupMemberAddRsp_ExtEntry_DoNotUseDefaultTypeInternal;
extern XmsgImGroupMemberAddRsp_ExtEntry_DoNotUseDefaultTypeInternal _XmsgImGroupMemberAddRsp_ExtEntry_DoNotUse_default_instance_;
class XmsgImGroupMemberDeleteReq;
class XmsgImGroupMemberDeleteReqDefaultTypeInternal;
extern XmsgImGroupMemberDeleteReqDefaultTypeInternal _XmsgImGroupMemberDeleteReq_default_instance_;
class XmsgImGroupMemberDeleteRsp;
class XmsgImGroupMemberDeleteRspDefaultTypeInternal;
extern XmsgImGroupMemberDeleteRspDefaultTypeInternal _XmsgImGroupMemberDeleteRsp_default_instance_;
class XmsgImGroupMemberDeleteRsp_ExtEntry_DoNotUse;
class XmsgImGroupMemberDeleteRsp_ExtEntry_DoNotUseDefaultTypeInternal;
extern XmsgImGroupMemberDeleteRsp_ExtEntry_DoNotUseDefaultTypeInternal _XmsgImGroupMemberDeleteRsp_ExtEntry_DoNotUse_default_instance_;
class XmsgImGroupMemberQueryReq;
class XmsgImGroupMemberQueryReqDefaultTypeInternal;
extern XmsgImGroupMemberQueryReqDefaultTypeInternal _XmsgImGroupMemberQueryReq_default_instance_;
class XmsgImGroupMemberQueryRsp;
class XmsgImGroupMemberQueryRspDefaultTypeInternal;
extern XmsgImGroupMemberQueryRspDefaultTypeInternal _XmsgImGroupMemberQueryRsp_default_instance_;
class XmsgImGroupMemberUpdateReq;
class XmsgImGroupMemberUpdateReqDefaultTypeInternal;
extern XmsgImGroupMemberUpdateReqDefaultTypeInternal _XmsgImGroupMemberUpdateReq_default_instance_;
class XmsgImGroupMemberUpdateReq_UpsertEntry_DoNotUse;
class XmsgImGroupMemberUpdateReq_UpsertEntry_DoNotUseDefaultTypeInternal;
extern XmsgImGroupMemberUpdateReq_UpsertEntry_DoNotUseDefaultTypeInternal _XmsgImGroupMemberUpdateReq_UpsertEntry_DoNotUse_default_instance_;
class XmsgImGroupMemberUpdateRsp;
class XmsgImGroupMemberUpdateRspDefaultTypeInternal;
extern XmsgImGroupMemberUpdateRspDefaultTypeInternal _XmsgImGroupMemberUpdateRsp_default_instance_;
class XmsgImGroupMemberUpdateRsp_ExtEntry_DoNotUse;
class XmsgImGroupMemberUpdateRsp_ExtEntry_DoNotUseDefaultTypeInternal;
extern XmsgImGroupMemberUpdateRsp_ExtEntry_DoNotUseDefaultTypeInternal _XmsgImGroupMemberUpdateRsp_ExtEntry_DoNotUse_default_instance_;

// ===================================================================

class XmsgImGroupMemberAddReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:XmsgImGroupMemberAddReq) */ {
 public:
  XmsgImGroupMemberAddReq();
  virtual ~XmsgImGroupMemberAddReq();

  XmsgImGroupMemberAddReq(const XmsgImGroupMemberAddReq& from);

  inline XmsgImGroupMemberAddReq& operator=(const XmsgImGroupMemberAddReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  XmsgImGroupMemberAddReq(XmsgImGroupMemberAddReq&& from) noexcept
    : XmsgImGroupMemberAddReq() {
    *this = ::std::move(from);
  }

  inline XmsgImGroupMemberAddReq& operator=(XmsgImGroupMemberAddReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const XmsgImGroupMemberAddReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const XmsgImGroupMemberAddReq* internal_default_instance() {
    return reinterpret_cast<const XmsgImGroupMemberAddReq*>(
               &_XmsgImGroupMemberAddReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(XmsgImGroupMemberAddReq* other);
  friend void swap(XmsgImGroupMemberAddReq& a, XmsgImGroupMemberAddReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline XmsgImGroupMemberAddReq* New() const PROTOBUF_FINAL { return New(NULL); }

  XmsgImGroupMemberAddReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const XmsgImGroupMemberAddReq& from);
  void MergeFrom(const XmsgImGroupMemberAddReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(XmsgImGroupMemberAddReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .XmsgImGroupAddMember member = 2;
  int member_size() const;
  void clear_member();
  static const int kMemberFieldNumber = 2;
  const ::XmsgImGroupAddMember& member(int index) const;
  ::XmsgImGroupAddMember* mutable_member(int index);
  ::XmsgImGroupAddMember* add_member();
  ::google::protobuf::RepeatedPtrField< ::XmsgImGroupAddMember >*
      mutable_member();
  const ::google::protobuf::RepeatedPtrField< ::XmsgImGroupAddMember >&
      member() const;

  // string cgt = 1;
  void clear_cgt();
  static const int kCgtFieldNumber = 1;
  const ::std::string& cgt() const;
  void set_cgt(const ::std::string& value);
  #if LANG_CXX11
  void set_cgt(::std::string&& value);
  #endif
  void set_cgt(const char* value);
  void set_cgt(const char* value, size_t size);
  ::std::string* mutable_cgt();
  ::std::string* release_cgt();
  void set_allocated_cgt(::std::string* cgt);

  // @@protoc_insertion_point(class_scope:XmsgImGroupMemberAddReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::XmsgImGroupAddMember > member_;
  ::google::protobuf::internal::ArenaStringPtr cgt_;
  mutable int _cached_size_;
  friend struct ::protobuf_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto::TableStruct;
  friend void ::protobuf_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto::InitDefaultsXmsgImGroupMemberAddReqImpl();
};
// -------------------------------------------------------------------

class XmsgImGroupMemberAddRsp_ExtEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<XmsgImGroupMemberAddRsp_ExtEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<XmsgImGroupMemberAddRsp_ExtEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  XmsgImGroupMemberAddRsp_ExtEntry_DoNotUse();
  XmsgImGroupMemberAddRsp_ExtEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const XmsgImGroupMemberAddRsp_ExtEntry_DoNotUse& other);
  static const XmsgImGroupMemberAddRsp_ExtEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const XmsgImGroupMemberAddRsp_ExtEntry_DoNotUse*>(&_XmsgImGroupMemberAddRsp_ExtEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class XmsgImGroupMemberAddRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:XmsgImGroupMemberAddRsp) */ {
 public:
  XmsgImGroupMemberAddRsp();
  virtual ~XmsgImGroupMemberAddRsp();

  XmsgImGroupMemberAddRsp(const XmsgImGroupMemberAddRsp& from);

  inline XmsgImGroupMemberAddRsp& operator=(const XmsgImGroupMemberAddRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  XmsgImGroupMemberAddRsp(XmsgImGroupMemberAddRsp&& from) noexcept
    : XmsgImGroupMemberAddRsp() {
    *this = ::std::move(from);
  }

  inline XmsgImGroupMemberAddRsp& operator=(XmsgImGroupMemberAddRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const XmsgImGroupMemberAddRsp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const XmsgImGroupMemberAddRsp* internal_default_instance() {
    return reinterpret_cast<const XmsgImGroupMemberAddRsp*>(
               &_XmsgImGroupMemberAddRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(XmsgImGroupMemberAddRsp* other);
  friend void swap(XmsgImGroupMemberAddRsp& a, XmsgImGroupMemberAddRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline XmsgImGroupMemberAddRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  XmsgImGroupMemberAddRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const XmsgImGroupMemberAddRsp& from);
  void MergeFrom(const XmsgImGroupMemberAddRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(XmsgImGroupMemberAddRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, string> ext = 1;
  int ext_size() const;
  void clear_ext();
  static const int kExtFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      ext() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_ext();

  // @@protoc_insertion_point(class_scope:XmsgImGroupMemberAddRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      XmsgImGroupMemberAddRsp_ExtEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > ext_;
  mutable int _cached_size_;
  friend struct ::protobuf_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto::TableStruct;
  friend void ::protobuf_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto::InitDefaultsXmsgImGroupMemberAddRspImpl();
};
// -------------------------------------------------------------------

class XmsgImGroupMemberQueryReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:XmsgImGroupMemberQueryReq) */ {
 public:
  XmsgImGroupMemberQueryReq();
  virtual ~XmsgImGroupMemberQueryReq();

  XmsgImGroupMemberQueryReq(const XmsgImGroupMemberQueryReq& from);

  inline XmsgImGroupMemberQueryReq& operator=(const XmsgImGroupMemberQueryReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  XmsgImGroupMemberQueryReq(XmsgImGroupMemberQueryReq&& from) noexcept
    : XmsgImGroupMemberQueryReq() {
    *this = ::std::move(from);
  }

  inline XmsgImGroupMemberQueryReq& operator=(XmsgImGroupMemberQueryReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const XmsgImGroupMemberQueryReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const XmsgImGroupMemberQueryReq* internal_default_instance() {
    return reinterpret_cast<const XmsgImGroupMemberQueryReq*>(
               &_XmsgImGroupMemberQueryReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(XmsgImGroupMemberQueryReq* other);
  friend void swap(XmsgImGroupMemberQueryReq& a, XmsgImGroupMemberQueryReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline XmsgImGroupMemberQueryReq* New() const PROTOBUF_FINAL { return New(NULL); }

  XmsgImGroupMemberQueryReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const XmsgImGroupMemberQueryReq& from);
  void MergeFrom(const XmsgImGroupMemberQueryReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(XmsgImGroupMemberQueryReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string mcgt = 2;
  int mcgt_size() const;
  void clear_mcgt();
  static const int kMcgtFieldNumber = 2;
  const ::std::string& mcgt(int index) const;
  ::std::string* mutable_mcgt(int index);
  void set_mcgt(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_mcgt(int index, ::std::string&& value);
  #endif
  void set_mcgt(int index, const char* value);
  void set_mcgt(int index, const char* value, size_t size);
  ::std::string* add_mcgt();
  void add_mcgt(const ::std::string& value);
  #if LANG_CXX11
  void add_mcgt(::std::string&& value);
  #endif
  void add_mcgt(const char* value);
  void add_mcgt(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& mcgt() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_mcgt();

  // string gcgt = 1;
  void clear_gcgt();
  static const int kGcgtFieldNumber = 1;
  const ::std::string& gcgt() const;
  void set_gcgt(const ::std::string& value);
  #if LANG_CXX11
  void set_gcgt(::std::string&& value);
  #endif
  void set_gcgt(const char* value);
  void set_gcgt(const char* value, size_t size);
  ::std::string* mutable_gcgt();
  ::std::string* release_gcgt();
  void set_allocated_gcgt(::std::string* gcgt);

  // @@protoc_insertion_point(class_scope:XmsgImGroupMemberQueryReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> mcgt_;
  ::google::protobuf::internal::ArenaStringPtr gcgt_;
  mutable int _cached_size_;
  friend struct ::protobuf_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto::TableStruct;
  friend void ::protobuf_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto::InitDefaultsXmsgImGroupMemberQueryReqImpl();
};
// -------------------------------------------------------------------

class XmsgImGroupMemberQueryRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:XmsgImGroupMemberQueryRsp) */ {
 public:
  XmsgImGroupMemberQueryRsp();
  virtual ~XmsgImGroupMemberQueryRsp();

  XmsgImGroupMemberQueryRsp(const XmsgImGroupMemberQueryRsp& from);

  inline XmsgImGroupMemberQueryRsp& operator=(const XmsgImGroupMemberQueryRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  XmsgImGroupMemberQueryRsp(XmsgImGroupMemberQueryRsp&& from) noexcept
    : XmsgImGroupMemberQueryRsp() {
    *this = ::std::move(from);
  }

  inline XmsgImGroupMemberQueryRsp& operator=(XmsgImGroupMemberQueryRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const XmsgImGroupMemberQueryRsp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const XmsgImGroupMemberQueryRsp* internal_default_instance() {
    return reinterpret_cast<const XmsgImGroupMemberQueryRsp*>(
               &_XmsgImGroupMemberQueryRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(XmsgImGroupMemberQueryRsp* other);
  friend void swap(XmsgImGroupMemberQueryRsp& a, XmsgImGroupMemberQueryRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline XmsgImGroupMemberQueryRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  XmsgImGroupMemberQueryRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const XmsgImGroupMemberQueryRsp& from);
  void MergeFrom(const XmsgImGroupMemberQueryRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(XmsgImGroupMemberQueryRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .XmsgImGroupInfoMember member = 1;
  int member_size() const;
  void clear_member();
  static const int kMemberFieldNumber = 1;
  const ::XmsgImGroupInfoMember& member(int index) const;
  ::XmsgImGroupInfoMember* mutable_member(int index);
  ::XmsgImGroupInfoMember* add_member();
  ::google::protobuf::RepeatedPtrField< ::XmsgImGroupInfoMember >*
      mutable_member();
  const ::google::protobuf::RepeatedPtrField< ::XmsgImGroupInfoMember >&
      member() const;

  // @@protoc_insertion_point(class_scope:XmsgImGroupMemberQueryRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::XmsgImGroupInfoMember > member_;
  mutable int _cached_size_;
  friend struct ::protobuf_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto::TableStruct;
  friend void ::protobuf_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto::InitDefaultsXmsgImGroupMemberQueryRspImpl();
};
// -------------------------------------------------------------------

class XmsgImGroupMemberUpdateReq_UpsertEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<XmsgImGroupMemberUpdateReq_UpsertEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<XmsgImGroupMemberUpdateReq_UpsertEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  XmsgImGroupMemberUpdateReq_UpsertEntry_DoNotUse();
  XmsgImGroupMemberUpdateReq_UpsertEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const XmsgImGroupMemberUpdateReq_UpsertEntry_DoNotUse& other);
  static const XmsgImGroupMemberUpdateReq_UpsertEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const XmsgImGroupMemberUpdateReq_UpsertEntry_DoNotUse*>(&_XmsgImGroupMemberUpdateReq_UpsertEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class XmsgImGroupMemberUpdateReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:XmsgImGroupMemberUpdateReq) */ {
 public:
  XmsgImGroupMemberUpdateReq();
  virtual ~XmsgImGroupMemberUpdateReq();

  XmsgImGroupMemberUpdateReq(const XmsgImGroupMemberUpdateReq& from);

  inline XmsgImGroupMemberUpdateReq& operator=(const XmsgImGroupMemberUpdateReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  XmsgImGroupMemberUpdateReq(XmsgImGroupMemberUpdateReq&& from) noexcept
    : XmsgImGroupMemberUpdateReq() {
    *this = ::std::move(from);
  }

  inline XmsgImGroupMemberUpdateReq& operator=(XmsgImGroupMemberUpdateReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const XmsgImGroupMemberUpdateReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const XmsgImGroupMemberUpdateReq* internal_default_instance() {
    return reinterpret_cast<const XmsgImGroupMemberUpdateReq*>(
               &_XmsgImGroupMemberUpdateReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(XmsgImGroupMemberUpdateReq* other);
  friend void swap(XmsgImGroupMemberUpdateReq& a, XmsgImGroupMemberUpdateReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline XmsgImGroupMemberUpdateReq* New() const PROTOBUF_FINAL { return New(NULL); }

  XmsgImGroupMemberUpdateReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const XmsgImGroupMemberUpdateReq& from);
  void MergeFrom(const XmsgImGroupMemberUpdateReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(XmsgImGroupMemberUpdateReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, string> upsert = 3;
  int upsert_size() const;
  void clear_upsert();
  static const int kUpsertFieldNumber = 3;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      upsert() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_upsert();

  // repeated string remove = 4;
  int remove_size() const;
  void clear_remove();
  static const int kRemoveFieldNumber = 4;
  const ::std::string& remove(int index) const;
  ::std::string* mutable_remove(int index);
  void set_remove(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_remove(int index, ::std::string&& value);
  #endif
  void set_remove(int index, const char* value);
  void set_remove(int index, const char* value, size_t size);
  ::std::string* add_remove();
  void add_remove(const ::std::string& value);
  #if LANG_CXX11
  void add_remove(::std::string&& value);
  #endif
  void add_remove(const char* value);
  void add_remove(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& remove() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_remove();

  // string gcgt = 1;
  void clear_gcgt();
  static const int kGcgtFieldNumber = 1;
  const ::std::string& gcgt() const;
  void set_gcgt(const ::std::string& value);
  #if LANG_CXX11
  void set_gcgt(::std::string&& value);
  #endif
  void set_gcgt(const char* value);
  void set_gcgt(const char* value, size_t size);
  ::std::string* mutable_gcgt();
  ::std::string* release_gcgt();
  void set_allocated_gcgt(::std::string* gcgt);

  // string mcgt = 2;
  void clear_mcgt();
  static const int kMcgtFieldNumber = 2;
  const ::std::string& mcgt() const;
  void set_mcgt(const ::std::string& value);
  #if LANG_CXX11
  void set_mcgt(::std::string&& value);
  #endif
  void set_mcgt(const char* value);
  void set_mcgt(const char* value, size_t size);
  ::std::string* mutable_mcgt();
  ::std::string* release_mcgt();
  void set_allocated_mcgt(::std::string* mcgt);

  // @@protoc_insertion_point(class_scope:XmsgImGroupMemberUpdateReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      XmsgImGroupMemberUpdateReq_UpsertEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > upsert_;
  ::google::protobuf::RepeatedPtrField< ::std::string> remove_;
  ::google::protobuf::internal::ArenaStringPtr gcgt_;
  ::google::protobuf::internal::ArenaStringPtr mcgt_;
  mutable int _cached_size_;
  friend struct ::protobuf_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto::TableStruct;
  friend void ::protobuf_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto::InitDefaultsXmsgImGroupMemberUpdateReqImpl();
};
// -------------------------------------------------------------------

class XmsgImGroupMemberUpdateRsp_ExtEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<XmsgImGroupMemberUpdateRsp_ExtEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<XmsgImGroupMemberUpdateRsp_ExtEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  XmsgImGroupMemberUpdateRsp_ExtEntry_DoNotUse();
  XmsgImGroupMemberUpdateRsp_ExtEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const XmsgImGroupMemberUpdateRsp_ExtEntry_DoNotUse& other);
  static const XmsgImGroupMemberUpdateRsp_ExtEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const XmsgImGroupMemberUpdateRsp_ExtEntry_DoNotUse*>(&_XmsgImGroupMemberUpdateRsp_ExtEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class XmsgImGroupMemberUpdateRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:XmsgImGroupMemberUpdateRsp) */ {
 public:
  XmsgImGroupMemberUpdateRsp();
  virtual ~XmsgImGroupMemberUpdateRsp();

  XmsgImGroupMemberUpdateRsp(const XmsgImGroupMemberUpdateRsp& from);

  inline XmsgImGroupMemberUpdateRsp& operator=(const XmsgImGroupMemberUpdateRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  XmsgImGroupMemberUpdateRsp(XmsgImGroupMemberUpdateRsp&& from) noexcept
    : XmsgImGroupMemberUpdateRsp() {
    *this = ::std::move(from);
  }

  inline XmsgImGroupMemberUpdateRsp& operator=(XmsgImGroupMemberUpdateRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const XmsgImGroupMemberUpdateRsp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const XmsgImGroupMemberUpdateRsp* internal_default_instance() {
    return reinterpret_cast<const XmsgImGroupMemberUpdateRsp*>(
               &_XmsgImGroupMemberUpdateRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(XmsgImGroupMemberUpdateRsp* other);
  friend void swap(XmsgImGroupMemberUpdateRsp& a, XmsgImGroupMemberUpdateRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline XmsgImGroupMemberUpdateRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  XmsgImGroupMemberUpdateRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const XmsgImGroupMemberUpdateRsp& from);
  void MergeFrom(const XmsgImGroupMemberUpdateRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(XmsgImGroupMemberUpdateRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, string> ext = 1;
  int ext_size() const;
  void clear_ext();
  static const int kExtFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      ext() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_ext();

  // @@protoc_insertion_point(class_scope:XmsgImGroupMemberUpdateRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      XmsgImGroupMemberUpdateRsp_ExtEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > ext_;
  mutable int _cached_size_;
  friend struct ::protobuf_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto::TableStruct;
  friend void ::protobuf_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto::InitDefaultsXmsgImGroupMemberUpdateRspImpl();
};
// -------------------------------------------------------------------

class XmsgImGroupMemberDeleteReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:XmsgImGroupMemberDeleteReq) */ {
 public:
  XmsgImGroupMemberDeleteReq();
  virtual ~XmsgImGroupMemberDeleteReq();

  XmsgImGroupMemberDeleteReq(const XmsgImGroupMemberDeleteReq& from);

  inline XmsgImGroupMemberDeleteReq& operator=(const XmsgImGroupMemberDeleteReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  XmsgImGroupMemberDeleteReq(XmsgImGroupMemberDeleteReq&& from) noexcept
    : XmsgImGroupMemberDeleteReq() {
    *this = ::std::move(from);
  }

  inline XmsgImGroupMemberDeleteReq& operator=(XmsgImGroupMemberDeleteReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const XmsgImGroupMemberDeleteReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const XmsgImGroupMemberDeleteReq* internal_default_instance() {
    return reinterpret_cast<const XmsgImGroupMemberDeleteReq*>(
               &_XmsgImGroupMemberDeleteReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    9;

  void Swap(XmsgImGroupMemberDeleteReq* other);
  friend void swap(XmsgImGroupMemberDeleteReq& a, XmsgImGroupMemberDeleteReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline XmsgImGroupMemberDeleteReq* New() const PROTOBUF_FINAL { return New(NULL); }

  XmsgImGroupMemberDeleteReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const XmsgImGroupMemberDeleteReq& from);
  void MergeFrom(const XmsgImGroupMemberDeleteReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(XmsgImGroupMemberDeleteReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string mcgt = 2;
  int mcgt_size() const;
  void clear_mcgt();
  static const int kMcgtFieldNumber = 2;
  const ::std::string& mcgt(int index) const;
  ::std::string* mutable_mcgt(int index);
  void set_mcgt(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_mcgt(int index, ::std::string&& value);
  #endif
  void set_mcgt(int index, const char* value);
  void set_mcgt(int index, const char* value, size_t size);
  ::std::string* add_mcgt();
  void add_mcgt(const ::std::string& value);
  #if LANG_CXX11
  void add_mcgt(::std::string&& value);
  #endif
  void add_mcgt(const char* value);
  void add_mcgt(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& mcgt() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_mcgt();

  // string gcgt = 1;
  void clear_gcgt();
  static const int kGcgtFieldNumber = 1;
  const ::std::string& gcgt() const;
  void set_gcgt(const ::std::string& value);
  #if LANG_CXX11
  void set_gcgt(::std::string&& value);
  #endif
  void set_gcgt(const char* value);
  void set_gcgt(const char* value, size_t size);
  ::std::string* mutable_gcgt();
  ::std::string* release_gcgt();
  void set_allocated_gcgt(::std::string* gcgt);

  // @@protoc_insertion_point(class_scope:XmsgImGroupMemberDeleteReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> mcgt_;
  ::google::protobuf::internal::ArenaStringPtr gcgt_;
  mutable int _cached_size_;
  friend struct ::protobuf_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto::TableStruct;
  friend void ::protobuf_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto::InitDefaultsXmsgImGroupMemberDeleteReqImpl();
};
// -------------------------------------------------------------------

class XmsgImGroupMemberDeleteRsp_ExtEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<XmsgImGroupMemberDeleteRsp_ExtEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<XmsgImGroupMemberDeleteRsp_ExtEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  XmsgImGroupMemberDeleteRsp_ExtEntry_DoNotUse();
  XmsgImGroupMemberDeleteRsp_ExtEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const XmsgImGroupMemberDeleteRsp_ExtEntry_DoNotUse& other);
  static const XmsgImGroupMemberDeleteRsp_ExtEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const XmsgImGroupMemberDeleteRsp_ExtEntry_DoNotUse*>(&_XmsgImGroupMemberDeleteRsp_ExtEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class XmsgImGroupMemberDeleteRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:XmsgImGroupMemberDeleteRsp) */ {
 public:
  XmsgImGroupMemberDeleteRsp();
  virtual ~XmsgImGroupMemberDeleteRsp();

  XmsgImGroupMemberDeleteRsp(const XmsgImGroupMemberDeleteRsp& from);

  inline XmsgImGroupMemberDeleteRsp& operator=(const XmsgImGroupMemberDeleteRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  XmsgImGroupMemberDeleteRsp(XmsgImGroupMemberDeleteRsp&& from) noexcept
    : XmsgImGroupMemberDeleteRsp() {
    *this = ::std::move(from);
  }

  inline XmsgImGroupMemberDeleteRsp& operator=(XmsgImGroupMemberDeleteRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const XmsgImGroupMemberDeleteRsp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const XmsgImGroupMemberDeleteRsp* internal_default_instance() {
    return reinterpret_cast<const XmsgImGroupMemberDeleteRsp*>(
               &_XmsgImGroupMemberDeleteRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    11;

  void Swap(XmsgImGroupMemberDeleteRsp* other);
  friend void swap(XmsgImGroupMemberDeleteRsp& a, XmsgImGroupMemberDeleteRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline XmsgImGroupMemberDeleteRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  XmsgImGroupMemberDeleteRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const XmsgImGroupMemberDeleteRsp& from);
  void MergeFrom(const XmsgImGroupMemberDeleteRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(XmsgImGroupMemberDeleteRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, string> ext = 1;
  int ext_size() const;
  void clear_ext();
  static const int kExtFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      ext() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_ext();

  // @@protoc_insertion_point(class_scope:XmsgImGroupMemberDeleteRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      XmsgImGroupMemberDeleteRsp_ExtEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > ext_;
  mutable int _cached_size_;
  friend struct ::protobuf_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto::TableStruct;
  friend void ::protobuf_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto::InitDefaultsXmsgImGroupMemberDeleteRspImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// XmsgImGroupMemberAddReq

// string cgt = 1;
inline void XmsgImGroupMemberAddReq::clear_cgt() {
  cgt_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XmsgImGroupMemberAddReq::cgt() const {
  // @@protoc_insertion_point(field_get:XmsgImGroupMemberAddReq.cgt)
  return cgt_.GetNoArena();
}
inline void XmsgImGroupMemberAddReq::set_cgt(const ::std::string& value) {
  
  cgt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:XmsgImGroupMemberAddReq.cgt)
}
#if LANG_CXX11
inline void XmsgImGroupMemberAddReq::set_cgt(::std::string&& value) {
  
  cgt_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:XmsgImGroupMemberAddReq.cgt)
}
#endif
inline void XmsgImGroupMemberAddReq::set_cgt(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  cgt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:XmsgImGroupMemberAddReq.cgt)
}
inline void XmsgImGroupMemberAddReq::set_cgt(const char* value, size_t size) {
  
  cgt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:XmsgImGroupMemberAddReq.cgt)
}
inline ::std::string* XmsgImGroupMemberAddReq::mutable_cgt() {
  
  // @@protoc_insertion_point(field_mutable:XmsgImGroupMemberAddReq.cgt)
  return cgt_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XmsgImGroupMemberAddReq::release_cgt() {
  // @@protoc_insertion_point(field_release:XmsgImGroupMemberAddReq.cgt)
  
  return cgt_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XmsgImGroupMemberAddReq::set_allocated_cgt(::std::string* cgt) {
  if (cgt != NULL) {
    
  } else {
    
  }
  cgt_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cgt);
  // @@protoc_insertion_point(field_set_allocated:XmsgImGroupMemberAddReq.cgt)
}

// repeated .XmsgImGroupAddMember member = 2;
inline int XmsgImGroupMemberAddReq::member_size() const {
  return member_.size();
}
inline const ::XmsgImGroupAddMember& XmsgImGroupMemberAddReq::member(int index) const {
  // @@protoc_insertion_point(field_get:XmsgImGroupMemberAddReq.member)
  return member_.Get(index);
}
inline ::XmsgImGroupAddMember* XmsgImGroupMemberAddReq::mutable_member(int index) {
  // @@protoc_insertion_point(field_mutable:XmsgImGroupMemberAddReq.member)
  return member_.Mutable(index);
}
inline ::XmsgImGroupAddMember* XmsgImGroupMemberAddReq::add_member() {
  // @@protoc_insertion_point(field_add:XmsgImGroupMemberAddReq.member)
  return member_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::XmsgImGroupAddMember >*
XmsgImGroupMemberAddReq::mutable_member() {
  // @@protoc_insertion_point(field_mutable_list:XmsgImGroupMemberAddReq.member)
  return &member_;
}
inline const ::google::protobuf::RepeatedPtrField< ::XmsgImGroupAddMember >&
XmsgImGroupMemberAddReq::member() const {
  // @@protoc_insertion_point(field_list:XmsgImGroupMemberAddReq.member)
  return member_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// XmsgImGroupMemberAddRsp

// map<string, string> ext = 1;
inline int XmsgImGroupMemberAddRsp::ext_size() const {
  return ext_.size();
}
inline void XmsgImGroupMemberAddRsp::clear_ext() {
  ext_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
XmsgImGroupMemberAddRsp::ext() const {
  // @@protoc_insertion_point(field_map:XmsgImGroupMemberAddRsp.ext)
  return ext_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
XmsgImGroupMemberAddRsp::mutable_ext() {
  // @@protoc_insertion_point(field_mutable_map:XmsgImGroupMemberAddRsp.ext)
  return ext_.MutableMap();
}

// -------------------------------------------------------------------

// XmsgImGroupMemberQueryReq

// string gcgt = 1;
inline void XmsgImGroupMemberQueryReq::clear_gcgt() {
  gcgt_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XmsgImGroupMemberQueryReq::gcgt() const {
  // @@protoc_insertion_point(field_get:XmsgImGroupMemberQueryReq.gcgt)
  return gcgt_.GetNoArena();
}
inline void XmsgImGroupMemberQueryReq::set_gcgt(const ::std::string& value) {
  
  gcgt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:XmsgImGroupMemberQueryReq.gcgt)
}
#if LANG_CXX11
inline void XmsgImGroupMemberQueryReq::set_gcgt(::std::string&& value) {
  
  gcgt_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:XmsgImGroupMemberQueryReq.gcgt)
}
#endif
inline void XmsgImGroupMemberQueryReq::set_gcgt(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  gcgt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:XmsgImGroupMemberQueryReq.gcgt)
}
inline void XmsgImGroupMemberQueryReq::set_gcgt(const char* value, size_t size) {
  
  gcgt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:XmsgImGroupMemberQueryReq.gcgt)
}
inline ::std::string* XmsgImGroupMemberQueryReq::mutable_gcgt() {
  
  // @@protoc_insertion_point(field_mutable:XmsgImGroupMemberQueryReq.gcgt)
  return gcgt_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XmsgImGroupMemberQueryReq::release_gcgt() {
  // @@protoc_insertion_point(field_release:XmsgImGroupMemberQueryReq.gcgt)
  
  return gcgt_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XmsgImGroupMemberQueryReq::set_allocated_gcgt(::std::string* gcgt) {
  if (gcgt != NULL) {
    
  } else {
    
  }
  gcgt_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), gcgt);
  // @@protoc_insertion_point(field_set_allocated:XmsgImGroupMemberQueryReq.gcgt)
}

// repeated string mcgt = 2;
inline int XmsgImGroupMemberQueryReq::mcgt_size() const {
  return mcgt_.size();
}
inline void XmsgImGroupMemberQueryReq::clear_mcgt() {
  mcgt_.Clear();
}
inline const ::std::string& XmsgImGroupMemberQueryReq::mcgt(int index) const {
  // @@protoc_insertion_point(field_get:XmsgImGroupMemberQueryReq.mcgt)
  return mcgt_.Get(index);
}
inline ::std::string* XmsgImGroupMemberQueryReq::mutable_mcgt(int index) {
  // @@protoc_insertion_point(field_mutable:XmsgImGroupMemberQueryReq.mcgt)
  return mcgt_.Mutable(index);
}
inline void XmsgImGroupMemberQueryReq::set_mcgt(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:XmsgImGroupMemberQueryReq.mcgt)
  mcgt_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void XmsgImGroupMemberQueryReq::set_mcgt(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:XmsgImGroupMemberQueryReq.mcgt)
  mcgt_.Mutable(index)->assign(std::move(value));
}
#endif
inline void XmsgImGroupMemberQueryReq::set_mcgt(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  mcgt_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:XmsgImGroupMemberQueryReq.mcgt)
}
inline void XmsgImGroupMemberQueryReq::set_mcgt(int index, const char* value, size_t size) {
  mcgt_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:XmsgImGroupMemberQueryReq.mcgt)
}
inline ::std::string* XmsgImGroupMemberQueryReq::add_mcgt() {
  // @@protoc_insertion_point(field_add_mutable:XmsgImGroupMemberQueryReq.mcgt)
  return mcgt_.Add();
}
inline void XmsgImGroupMemberQueryReq::add_mcgt(const ::std::string& value) {
  mcgt_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:XmsgImGroupMemberQueryReq.mcgt)
}
#if LANG_CXX11
inline void XmsgImGroupMemberQueryReq::add_mcgt(::std::string&& value) {
  mcgt_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:XmsgImGroupMemberQueryReq.mcgt)
}
#endif
inline void XmsgImGroupMemberQueryReq::add_mcgt(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  mcgt_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:XmsgImGroupMemberQueryReq.mcgt)
}
inline void XmsgImGroupMemberQueryReq::add_mcgt(const char* value, size_t size) {
  mcgt_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:XmsgImGroupMemberQueryReq.mcgt)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
XmsgImGroupMemberQueryReq::mcgt() const {
  // @@protoc_insertion_point(field_list:XmsgImGroupMemberQueryReq.mcgt)
  return mcgt_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
XmsgImGroupMemberQueryReq::mutable_mcgt() {
  // @@protoc_insertion_point(field_mutable_list:XmsgImGroupMemberQueryReq.mcgt)
  return &mcgt_;
}

// -------------------------------------------------------------------

// XmsgImGroupMemberQueryRsp

// repeated .XmsgImGroupInfoMember member = 1;
inline int XmsgImGroupMemberQueryRsp::member_size() const {
  return member_.size();
}
inline const ::XmsgImGroupInfoMember& XmsgImGroupMemberQueryRsp::member(int index) const {
  // @@protoc_insertion_point(field_get:XmsgImGroupMemberQueryRsp.member)
  return member_.Get(index);
}
inline ::XmsgImGroupInfoMember* XmsgImGroupMemberQueryRsp::mutable_member(int index) {
  // @@protoc_insertion_point(field_mutable:XmsgImGroupMemberQueryRsp.member)
  return member_.Mutable(index);
}
inline ::XmsgImGroupInfoMember* XmsgImGroupMemberQueryRsp::add_member() {
  // @@protoc_insertion_point(field_add:XmsgImGroupMemberQueryRsp.member)
  return member_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::XmsgImGroupInfoMember >*
XmsgImGroupMemberQueryRsp::mutable_member() {
  // @@protoc_insertion_point(field_mutable_list:XmsgImGroupMemberQueryRsp.member)
  return &member_;
}
inline const ::google::protobuf::RepeatedPtrField< ::XmsgImGroupInfoMember >&
XmsgImGroupMemberQueryRsp::member() const {
  // @@protoc_insertion_point(field_list:XmsgImGroupMemberQueryRsp.member)
  return member_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// XmsgImGroupMemberUpdateReq

// string gcgt = 1;
inline void XmsgImGroupMemberUpdateReq::clear_gcgt() {
  gcgt_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XmsgImGroupMemberUpdateReq::gcgt() const {
  // @@protoc_insertion_point(field_get:XmsgImGroupMemberUpdateReq.gcgt)
  return gcgt_.GetNoArena();
}
inline void XmsgImGroupMemberUpdateReq::set_gcgt(const ::std::string& value) {
  
  gcgt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:XmsgImGroupMemberUpdateReq.gcgt)
}
#if LANG_CXX11
inline void XmsgImGroupMemberUpdateReq::set_gcgt(::std::string&& value) {
  
  gcgt_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:XmsgImGroupMemberUpdateReq.gcgt)
}
#endif
inline void XmsgImGroupMemberUpdateReq::set_gcgt(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  gcgt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:XmsgImGroupMemberUpdateReq.gcgt)
}
inline void XmsgImGroupMemberUpdateReq::set_gcgt(const char* value, size_t size) {
  
  gcgt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:XmsgImGroupMemberUpdateReq.gcgt)
}
inline ::std::string* XmsgImGroupMemberUpdateReq::mutable_gcgt() {
  
  // @@protoc_insertion_point(field_mutable:XmsgImGroupMemberUpdateReq.gcgt)
  return gcgt_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XmsgImGroupMemberUpdateReq::release_gcgt() {
  // @@protoc_insertion_point(field_release:XmsgImGroupMemberUpdateReq.gcgt)
  
  return gcgt_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XmsgImGroupMemberUpdateReq::set_allocated_gcgt(::std::string* gcgt) {
  if (gcgt != NULL) {
    
  } else {
    
  }
  gcgt_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), gcgt);
  // @@protoc_insertion_point(field_set_allocated:XmsgImGroupMemberUpdateReq.gcgt)
}

// string mcgt = 2;
inline void XmsgImGroupMemberUpdateReq::clear_mcgt() {
  mcgt_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XmsgImGroupMemberUpdateReq::mcgt() const {
  // @@protoc_insertion_point(field_get:XmsgImGroupMemberUpdateReq.mcgt)
  return mcgt_.GetNoArena();
}
inline void XmsgImGroupMemberUpdateReq::set_mcgt(const ::std::string& value) {
  
  mcgt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:XmsgImGroupMemberUpdateReq.mcgt)
}
#if LANG_CXX11
inline void XmsgImGroupMemberUpdateReq::set_mcgt(::std::string&& value) {
  
  mcgt_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:XmsgImGroupMemberUpdateReq.mcgt)
}
#endif
inline void XmsgImGroupMemberUpdateReq::set_mcgt(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  mcgt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:XmsgImGroupMemberUpdateReq.mcgt)
}
inline void XmsgImGroupMemberUpdateReq::set_mcgt(const char* value, size_t size) {
  
  mcgt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:XmsgImGroupMemberUpdateReq.mcgt)
}
inline ::std::string* XmsgImGroupMemberUpdateReq::mutable_mcgt() {
  
  // @@protoc_insertion_point(field_mutable:XmsgImGroupMemberUpdateReq.mcgt)
  return mcgt_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XmsgImGroupMemberUpdateReq::release_mcgt() {
  // @@protoc_insertion_point(field_release:XmsgImGroupMemberUpdateReq.mcgt)
  
  return mcgt_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XmsgImGroupMemberUpdateReq::set_allocated_mcgt(::std::string* mcgt) {
  if (mcgt != NULL) {
    
  } else {
    
  }
  mcgt_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mcgt);
  // @@protoc_insertion_point(field_set_allocated:XmsgImGroupMemberUpdateReq.mcgt)
}

// map<string, string> upsert = 3;
inline int XmsgImGroupMemberUpdateReq::upsert_size() const {
  return upsert_.size();
}
inline void XmsgImGroupMemberUpdateReq::clear_upsert() {
  upsert_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
XmsgImGroupMemberUpdateReq::upsert() const {
  // @@protoc_insertion_point(field_map:XmsgImGroupMemberUpdateReq.upsert)
  return upsert_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
XmsgImGroupMemberUpdateReq::mutable_upsert() {
  // @@protoc_insertion_point(field_mutable_map:XmsgImGroupMemberUpdateReq.upsert)
  return upsert_.MutableMap();
}

// repeated string remove = 4;
inline int XmsgImGroupMemberUpdateReq::remove_size() const {
  return remove_.size();
}
inline void XmsgImGroupMemberUpdateReq::clear_remove() {
  remove_.Clear();
}
inline const ::std::string& XmsgImGroupMemberUpdateReq::remove(int index) const {
  // @@protoc_insertion_point(field_get:XmsgImGroupMemberUpdateReq.remove)
  return remove_.Get(index);
}
inline ::std::string* XmsgImGroupMemberUpdateReq::mutable_remove(int index) {
  // @@protoc_insertion_point(field_mutable:XmsgImGroupMemberUpdateReq.remove)
  return remove_.Mutable(index);
}
inline void XmsgImGroupMemberUpdateReq::set_remove(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:XmsgImGroupMemberUpdateReq.remove)
  remove_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void XmsgImGroupMemberUpdateReq::set_remove(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:XmsgImGroupMemberUpdateReq.remove)
  remove_.Mutable(index)->assign(std::move(value));
}
#endif
inline void XmsgImGroupMemberUpdateReq::set_remove(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  remove_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:XmsgImGroupMemberUpdateReq.remove)
}
inline void XmsgImGroupMemberUpdateReq::set_remove(int index, const char* value, size_t size) {
  remove_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:XmsgImGroupMemberUpdateReq.remove)
}
inline ::std::string* XmsgImGroupMemberUpdateReq::add_remove() {
  // @@protoc_insertion_point(field_add_mutable:XmsgImGroupMemberUpdateReq.remove)
  return remove_.Add();
}
inline void XmsgImGroupMemberUpdateReq::add_remove(const ::std::string& value) {
  remove_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:XmsgImGroupMemberUpdateReq.remove)
}
#if LANG_CXX11
inline void XmsgImGroupMemberUpdateReq::add_remove(::std::string&& value) {
  remove_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:XmsgImGroupMemberUpdateReq.remove)
}
#endif
inline void XmsgImGroupMemberUpdateReq::add_remove(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  remove_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:XmsgImGroupMemberUpdateReq.remove)
}
inline void XmsgImGroupMemberUpdateReq::add_remove(const char* value, size_t size) {
  remove_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:XmsgImGroupMemberUpdateReq.remove)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
XmsgImGroupMemberUpdateReq::remove() const {
  // @@protoc_insertion_point(field_list:XmsgImGroupMemberUpdateReq.remove)
  return remove_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
XmsgImGroupMemberUpdateReq::mutable_remove() {
  // @@protoc_insertion_point(field_mutable_list:XmsgImGroupMemberUpdateReq.remove)
  return &remove_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// XmsgImGroupMemberUpdateRsp

// map<string, string> ext = 1;
inline int XmsgImGroupMemberUpdateRsp::ext_size() const {
  return ext_.size();
}
inline void XmsgImGroupMemberUpdateRsp::clear_ext() {
  ext_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
XmsgImGroupMemberUpdateRsp::ext() const {
  // @@protoc_insertion_point(field_map:XmsgImGroupMemberUpdateRsp.ext)
  return ext_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
XmsgImGroupMemberUpdateRsp::mutable_ext() {
  // @@protoc_insertion_point(field_mutable_map:XmsgImGroupMemberUpdateRsp.ext)
  return ext_.MutableMap();
}

// -------------------------------------------------------------------

// XmsgImGroupMemberDeleteReq

// string gcgt = 1;
inline void XmsgImGroupMemberDeleteReq::clear_gcgt() {
  gcgt_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XmsgImGroupMemberDeleteReq::gcgt() const {
  // @@protoc_insertion_point(field_get:XmsgImGroupMemberDeleteReq.gcgt)
  return gcgt_.GetNoArena();
}
inline void XmsgImGroupMemberDeleteReq::set_gcgt(const ::std::string& value) {
  
  gcgt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:XmsgImGroupMemberDeleteReq.gcgt)
}
#if LANG_CXX11
inline void XmsgImGroupMemberDeleteReq::set_gcgt(::std::string&& value) {
  
  gcgt_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:XmsgImGroupMemberDeleteReq.gcgt)
}
#endif
inline void XmsgImGroupMemberDeleteReq::set_gcgt(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  gcgt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:XmsgImGroupMemberDeleteReq.gcgt)
}
inline void XmsgImGroupMemberDeleteReq::set_gcgt(const char* value, size_t size) {
  
  gcgt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:XmsgImGroupMemberDeleteReq.gcgt)
}
inline ::std::string* XmsgImGroupMemberDeleteReq::mutable_gcgt() {
  
  // @@protoc_insertion_point(field_mutable:XmsgImGroupMemberDeleteReq.gcgt)
  return gcgt_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XmsgImGroupMemberDeleteReq::release_gcgt() {
  // @@protoc_insertion_point(field_release:XmsgImGroupMemberDeleteReq.gcgt)
  
  return gcgt_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XmsgImGroupMemberDeleteReq::set_allocated_gcgt(::std::string* gcgt) {
  if (gcgt != NULL) {
    
  } else {
    
  }
  gcgt_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), gcgt);
  // @@protoc_insertion_point(field_set_allocated:XmsgImGroupMemberDeleteReq.gcgt)
}

// repeated string mcgt = 2;
inline int XmsgImGroupMemberDeleteReq::mcgt_size() const {
  return mcgt_.size();
}
inline void XmsgImGroupMemberDeleteReq::clear_mcgt() {
  mcgt_.Clear();
}
inline const ::std::string& XmsgImGroupMemberDeleteReq::mcgt(int index) const {
  // @@protoc_insertion_point(field_get:XmsgImGroupMemberDeleteReq.mcgt)
  return mcgt_.Get(index);
}
inline ::std::string* XmsgImGroupMemberDeleteReq::mutable_mcgt(int index) {
  // @@protoc_insertion_point(field_mutable:XmsgImGroupMemberDeleteReq.mcgt)
  return mcgt_.Mutable(index);
}
inline void XmsgImGroupMemberDeleteReq::set_mcgt(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:XmsgImGroupMemberDeleteReq.mcgt)
  mcgt_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void XmsgImGroupMemberDeleteReq::set_mcgt(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:XmsgImGroupMemberDeleteReq.mcgt)
  mcgt_.Mutable(index)->assign(std::move(value));
}
#endif
inline void XmsgImGroupMemberDeleteReq::set_mcgt(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  mcgt_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:XmsgImGroupMemberDeleteReq.mcgt)
}
inline void XmsgImGroupMemberDeleteReq::set_mcgt(int index, const char* value, size_t size) {
  mcgt_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:XmsgImGroupMemberDeleteReq.mcgt)
}
inline ::std::string* XmsgImGroupMemberDeleteReq::add_mcgt() {
  // @@protoc_insertion_point(field_add_mutable:XmsgImGroupMemberDeleteReq.mcgt)
  return mcgt_.Add();
}
inline void XmsgImGroupMemberDeleteReq::add_mcgt(const ::std::string& value) {
  mcgt_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:XmsgImGroupMemberDeleteReq.mcgt)
}
#if LANG_CXX11
inline void XmsgImGroupMemberDeleteReq::add_mcgt(::std::string&& value) {
  mcgt_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:XmsgImGroupMemberDeleteReq.mcgt)
}
#endif
inline void XmsgImGroupMemberDeleteReq::add_mcgt(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  mcgt_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:XmsgImGroupMemberDeleteReq.mcgt)
}
inline void XmsgImGroupMemberDeleteReq::add_mcgt(const char* value, size_t size) {
  mcgt_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:XmsgImGroupMemberDeleteReq.mcgt)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
XmsgImGroupMemberDeleteReq::mcgt() const {
  // @@protoc_insertion_point(field_list:XmsgImGroupMemberDeleteReq.mcgt)
  return mcgt_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
XmsgImGroupMemberDeleteReq::mutable_mcgt() {
  // @@protoc_insertion_point(field_mutable_list:XmsgImGroupMemberDeleteReq.mcgt)
  return &mcgt_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// XmsgImGroupMemberDeleteRsp

// map<string, string> ext = 1;
inline int XmsgImGroupMemberDeleteRsp::ext_size() const {
  return ext_.size();
}
inline void XmsgImGroupMemberDeleteRsp::clear_ext() {
  ext_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
XmsgImGroupMemberDeleteRsp::ext() const {
  // @@protoc_insertion_point(field_map:XmsgImGroupMemberDeleteRsp.ext)
  return ext_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
XmsgImGroupMemberDeleteRsp::mutable_ext() {
  // @@protoc_insertion_point(field_mutable_map:XmsgImGroupMemberDeleteRsp.ext)
  return ext_.MutableMap();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_net_2dx_2dmsg_2dim_2dgroup_2dmember_2eproto__INCLUDED
